### ISSUE TITLE
Spammers sending malicious links in NAME field

### ISSUE THREAD

**Issue by JeffMash** [torvista/Zen_Cart-Back_in_Stock_Notifications#16]
It seems that spammers are using the module to send SPAM LINKS which contain malicious links in the NAME field.

The module only asks for three fields: Name, Email Address, and Confirm Email Address.   What is happening is that they put a legitimate email address in the two fields (the person they want to spam), but they put their malicious link in the NAME field.  Since the form is submitted and authenticated by our own SMTP domain, it isn't seen as SPAM (since our domain is originating the email) and it gets sent to the customer.

Here is a screenshot of what the SPAM looks like: https://i.postimg.cc/c15tMdZj/screenshot-132.png

Notice that in this example, the NAME FIELD that the spammer used was: "🍒 Amber want to play with you! Start Game: https://letsg0dancing.page.link/go?exx 🍒"

So when the recipient (whose address is entered in the email field) opens the Back In Stock email, the very first line (which is the NAME field) contains the malicious link.

SOME THOUGHTS ON ADDRESSING THE ISSUE:

1.  Some sort of CAPTCHA might be applied to help reduce automated spammers from abusing the form.   However, this won't stop spammers from manually entering in the information.

2.  At the very least, perhaps run a string-check on the NAME and reject anything that is 1) over a certain amount of characters, and 2) reject anything that has an "HTTP" or ".com" in it, and 3) reject any name with "more than two blank spaces" in it.   

That alone should weed out most fake names, since most names won't be over about 10 characters, and most won't have a www/http string, and most won't have more than two blank spaces (John Smith Jr, etc).

3.  As a complete fail-safe, perhaps having an option to DISABLE the NAME field would work.    In other words, only allow an email address to be entered.   This would still "spam" though, but it won't contain  any malicious links because there would be no name field.

**Comment by torvista** [comment]
Hmm, just got one.

**Comment by torvista** [comment]
I've updated this 
https://github.com/torvista/Zen_Cart-Google_reCAPTCHA
to allow for BISN.
