### ISSUE TITLE
Date format in \includes\modules\pages\back_in_stock_notification_subscribe\header_php.php

### ISSUE THREAD

**Issue by OldNGreyBMR** [torvista/Zen_Cart-Back_in_Stock_Notifications#17]
In  \includes\modules\pages\back_in_stock_notification_subscribeLine\header_php.php
line 193 has the date format as
'date_subscribed' => date('Y-m-d H:m:i')
I believe that it should be 'date_subscribed' => date('Y-m-d H:m:i')

**Comment by torvista** [comment]
You suggestion has been mangled by markup, what problem shows up with this and could you rewrite the fix?

**Comment by OldNGreyBMR** [comment]
lines 193 and 217 have date subscribed as 'Y-m-d H:\m:i [ NOTE m is escaped to avoid reformatting by this reporting system] which is Year (YYYY) Month (00) Day (00) then Hour (00) month (00) seconds (00)
the format should be 'Y-m-d H:i:s'
This issue only shows up when I change the Date subscribed displayed in Admin to the stored date. I use the admin report to cross match to restocking orders.  Most people would never notice it.

**Comment by torvista** [comment]
thanks
fixed: https://github.com/torvista/Zen_Cart-Back_in_Stock_Notifications/pull/22
